# Generated by Django 4.0.5 on 2022-06-25 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("movie_app", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="review",
            name="start",
            field=models.IntegerField(
                choices=[(1, "*"), (2, "**"), (3, "***"), (4, "****"), (5, "*****")],
                default=0,
                null=True,
            ),
        ),
    ]
